# Generated by Django 6.0.2 on 2026-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='blockchain_escrow_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
